apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crpaas.fullname" . }}-opengrok
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
    app.kubernetes.io/component: opengrok
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "crpaas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: opengrok
  template:
    metadata:
      labels:
        {{- include "crpaas.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: opengrok
    spec:
      containers:
        - name: opengrok
          image: "{{ .Values.opengrok.image.repository }}:{{ .Values.opengrok.image.tag }}"
          imagePullPolicy: {{ .Values.opengrok.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.opengrok.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.opengrok.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.opengrok.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.opengrok.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.opengrok.resources | nindent 12 }}
          volumeMounts:
            - name: source-code
              mountPath: /opengrok/src
              readOnly: false
            - name: opengrok-data
              mountPath: /opengrok/data
            - name: cloner-script
              mountPath: /custom-scripts
              readOnly: true
            - name: ssh-volume
              mountPath: /etc/git-secret
              readOnly: true
      volumes:
        - name: source-code
          persistentVolumeClaim:
            claimName: {{ include "crpaas.fullname" . }}-source-code
        - name: opengrok-data
          persistentVolumeClaim:
            claimName: {{ include "crpaas.fullname" . }}-opengrok-data
        - name: cloner-script
          configMap:
            name: {{ include "crpaas.fullname" . }}-cloner-script
            defaultMode: 0755
        - name: ssh-volume
          projected:
            defaultMode: 0644
            sources:
              - secret:
                  name: {{ .Values.crpaasManager.gitSsh.secretName }}
                  items:
                    - key: {{ .Values.crpaasManager.gitSsh.sshKeyFileKey }}
                      path: id_rsa
                      mode: 0400
              - configMap:
                  name: ssh-config-ssh-config
                  items:
                    - key: config
                      path: config
                      mode: 0400