{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crpaas.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crpaas.fullname" . }}-job-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "create", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crpaas.fullname" . }}-job-creator-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crpaas.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "crpaas.fullname" . }}-job-creator
  apiGroup: rbac.authorization.k8s.io
{{- end }}