apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crpaas.fullname" . }}-source-code
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.source.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.source.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crpaas.fullname" . }}-opengrok-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.data.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crpaas.fullname" . }}-manager-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crpaas.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.manager.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.manager.size }}